apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project-posted
  name: project-posted
  labels:
    app: project-posted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-posted
  template:
    metadata:
      labels:
        app: project-posted
    spec:
      containers:
      - name: project-posted
        image: devlaunchers/project_posted:latest
        ports:
        - containerPort: 4000
        resources:
          limits:
            cpu: 250m
            memory: 160Mi
          requests:
            cpu: 50m
            memory: 32Mi